hadoop:
  namenodes:
    - nameservices: logs-hdfs
      namenodesAddr: [ "host1", "host2" ]
      namenodes: [ "namenode1", "namenode2" ]
      user: hdfs
      password:
      port: 8020
      matchPathKeys: [ "flume" ]

  yarn:
    - clusterName: "IDC"
      resourceManager: [ "pro-hadooprm-dc01-003011.vm.dc01.hellocloud.tech:8088" ]
      jobHistoryServer: "pro-hadoophistoryserver-dc01-009116.vm.dc01.hellocloud.tech:19888"

  spark:
    sparkHistoryServer: [ "shs.hellobike.cn" ]
