server:
  port: 7072

spring:
  profiles:
    active: hadoop
  task:
    scheduling:
      pool:
        size: 10
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8

  opensearch:
    nodes: localhost:19527
    username:
    password:
    truststore:
    truststore-password:
    yarn-app-prefix: "compass-yarn-app-"
    spark-app-prefix: "compass-spark-app-"

scheduler:
  clusterMeta:
    enable: true
    cron: "0 */30 * * * ?"
  yarnMeta:
    enable: true
    cron: "0/30 * * * * ?"
    # hour
    startedTimeBegin: 6
  sparkMeta:
    enable: true
    cron: "0/30 * * * * ?"
    limitCount: 1000
